### ISSUE TITLE
any chance this will compile for armv6 ?

### ISSUE THREAD

**Issue by bluwave** [mooncatventures-group/ffmpegDecoder#1]
I can't seem to compile this for armv6, any tips or advice ?

**Comment by mooncatventures-group** [comment]
The resource requirements are so high, it didn't make a lot of sense to cover legacy devices.
If you like I can help you build the ffmpeg libs for armv6 and recompile the framework.
give me a few days to get back with you, we are awfully busy right now.

The ffmpeg.zip with mods is in one of our repositories, I don't remember which one.

michelle :-)

**Comment by bluwave** [comment]
thanks

**Comment by bluwave** [comment]
michelle, 

i have another question for you.  Do you know how many fps this lib would be displaying video at ?  If it is 25 fps, how could we get it to 20 fps or 30 fps.  We've been having a latency issue.  Any ideas?  Thanks for all your help, its really appreciated.

**Comment by Rcowart** [comment]
Michelle,

I work with bluwave :)  Our problem is we are seeing a delay when streaming over rtsp with tcp, and that delay gets longer the longer we stream (out to 7-8 minutes and beyond).  So the theory is that because our stream is 30fps and ffmpeg seems (according to docs) fixed at 25 fps, that's causing the issue.

**Comment by mooncatventures-group** [comment]
which one of our frameworks are you trying too use
Not all of our frameworks are in the public domain , but we certainly can offer some consulting if your interested.

Here what we are finding

Startup delay around 3 - 4 seconds, part of this is the 1.5 second delay common with using Apple core audio  AudioQueue api, RemoteIO givers better performance but is  a lot tricker to implement. check out RTSplay if you haven't already.

We see aprox 3 to 4 second delay between realtime and camera when streaming audio and video.  A very lot depends on how buffering you do, the bigger buffers for audio and video cause longer delays. But these are consistent delays that  do not vary while streaming.
perhaps you are seeing network issues, or loss packets? look at FFplay-tests, there's a small startup delay, but no realtime vs camera delay. Then again there is no audio , so we just take each packet as we get it. No opengl overhead either since it uses uiimage. Down side of that is video breaks up badly over weak connections. I think a lot of commercial video players use this technique which is so much easier than open gl but gives bad performance.

I would go with 20 - 25 fps , the human eye cannot discern the difference between 20- 30 fps, and will just put it together as fluid motion. a lot of commercial players operate at 15 fps.

There's more I can give you if your interested in working with us, but I'd rather discuss privately, if you want send us a contact email address. michelle@mooncatventures.com

**Comment by mooncatventures-group** [comment]
You mean 7 - 8 seconds don't you not seven to eight minutes :-)

**Comment by Rcowart** [comment]
Thank you for responding.  no i mean 7-8 minutes  I will send you an email and copy bluwave.

**Comment by Rcowart** [comment]
i think the most I've actually seen is 3 minutes.  but some of the testers have suggested crazy numbers.
